"use server";

import { clerkClient } from "@clerk/nextjs/server";

interface CalendarEvent {
  summary: string;
  description: string;
  start: { dateTime: string; timeZone: string };
  end: { dateTime: string; timeZone: string };
  reminders: {
    useDefault: boolean;
    overrides: Array<{ method: string; minutes: number }>;
  };
}

export async function createFlashcardReminders(
  userId: string,
  flashcardTitle: string,
  chatTitle: string,
  chatId: string
): Promise<boolean> {
  try {
    const client = await clerkClient();
    const tokenResponse = await client.users.getUserOauthAccessToken(
      userId,
      "oauth_google"
    );

    if (!tokenResponse.data || tokenResponse.data.length === 0) {
      console.error("No Google OAuth token found for user");
      return false;
    }

    const accessToken = tokenResponse.data[0].token;
    const creationDate = new Date();

    // Spaced repetition schedule: 3, 5, 7, 9 days
    const scheduleOffsets = [3, 5, 7, 9];
    const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;

    const reviewUrl = `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/chat/${chatId}`;

    const events: CalendarEvent[] = scheduleOffsets.map((offset, index) => {
      const reminderDate = new Date(creationDate);
      reminderDate.setDate(reminderDate.getDate() + offset);
      reminderDate.setHours(12, 0, 0, 0); // Set to noon

      const endTime = new Date(reminderDate);
      endTime.setMinutes(endTime.getMinutes() + 30);

      return {
        summary: `📚 Flashcard Review - ${flashcardTitle}`,
        description: `Time to review your flashcards from "${chatTitle}"!

This is reminder ${index + 1} of 4 in your spaced repetition schedule.

🧠 Spaced repetition helps improve long-term retention by reviewing material at increasing intervals.

🔗 Click here to review: ${reviewUrl}

Generated by VibeNote`,
        start: {
          dateTime: reminderDate.toISOString(),
          timeZone: timeZone,
        },
        end: {
          dateTime: endTime.toISOString(),
          timeZone: timeZone,
        },
        reminders: {
          useDefault: false,
          overrides: [
            {
              method: "popup",
              minutes: 15,
            },
            {
              method: "email",
              minutes: 60,
            },
          ],
        },
      };
    });

    // Create all calendar events
    const results = await Promise.allSettled(
      events.map(async (event) => {
        const response = await fetch(
          "https://www.googleapis.com/calendar/v3/calendars/primary/events",
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${accessToken}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify(event),
          }
        );

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(
            `Failed to create calendar event: ${response.status} ${errorText}`
          );
        }

        return await response.json();
      })
    );

    const failedEvents = results.filter(
      (result) => result.status === "rejected"
    );

    if (failedEvents.length > 0) {
      console.error("Some calendar events failed to create:", failedEvents);
      return false;
    }

    console.log(
      `Successfully created ${results.length} flashcard reminder events`
    );
    return true;
  } catch (error) {
    console.error("Error creating flashcard reminders:", error);
    return false;
  }
}
